# Project information
site_name: Openterface Mini-KVM | Turn Your Laptop into a KVM Console
site_url: https://openterface.com/
site_author: Billy Wang
site_description: A Feature-rich, Open-source and Community-driven KVM-over-USB Solution

# Repository
repo_name: Openterface
repo_url: https://github.com/TechxArtisan/Openterface

# Copyright
copyright: >-
  Copyright &copy; All rights reserved. 2023 <a href="https://www.openterface.com">Openterface MiniKVM</a>, Guangzhou Billio Tech. Co., Ltd. <br>
  <a href="">Home</a> |
  <a href="/terms-of-service">Terms of Service</a> |
  <a href="/privacy-policy">Privacy Policy</a> | 
  <a href="#__consent">Cookie Settings</a> | 
  <a href="/contact">Contact Us</a>


extra_css:
  - assets/stylesheets/extra.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - navigation.indexes
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
  palette:
    primary: deep orange
    accent: custom

extra:
  social:
    - icon: txa/crowd-supply-icon
      link: https://www.crowdsupply.com/techxartisan/openterface-mini-kvm
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/Openterface_miniKVM/
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/skfExqDD
    # - icon: fontawesome/brands/github-alt
    #   link: https://github.com/TechxArtisan
  
  alternate:
    - name: English 🇺🇸🇬🇧🇨🇦🇦🇺
      link: /
      lang: en
    # - name: 中文简体 🇨🇳
    #   link: https://zh.openterface.com/
    #   lang: zh
    # - name: 中文繁體 🇭🇰
    #   link: https://tw.openterface.com/
    #   lang: zh-Hant
    # - name: 日本語 🇯🇵
    #   link: https://jp.openterface.com/
    #   lang: ja
    # - name: 한국어 🇰🇷
    #   link: https://kr.openterface.com/
    #   lang: ko
    # - name: Français 🇫🇷
    #   link: https://fr.openterface.com/
    #   lang: fr
    # - name: Deutsch 🇩🇪
    #   link: https://de.openterface.com/
    #   lang: de
    # - name: Italiano 🇮🇹
    #   link: https://it.openterface.com/
    #   lang: it
    # - name: Español 🇪🇸
    #   link: https://es.openterface.com/
    #   lang: es
    # - name: Português 🇵🇹
    #   link: https://pt.openterface.com/
    #   lang: pt
    # - name: Svenska 🇸🇪
    #   link: https://sv.openterface.com/
    #   lang: sv
    # - name: Polski 🇵🇱
    #   link: https://pl.openterface.com/
    #   lang: pl
    # - name: Nederlands 🇳🇱
    #   link: https://nl.openterface.com/
    #   lang: nl

  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-EKZEH6QYWT
    # feedback:
    #   title: Was this page helpful?
    #   ratings:
    #     - icon: material/heart
    #       name: This page was helpful
    #       data: 1
    #       note: >-
    #         Thanks for your feedback!
    #     - icon: material/heart-broken
    #       name: This page could be improved
    #       data: 0
    #       note: >- 
    #         Thanks for your feedback! Help us improve this page by
    #         using our <a href="https://forms.gle/7AoXW2YCPMfmpRmr5" target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
              custom_icons:
                - overrides/.icons

plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{slug}"
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      categories_name: Categories
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false

nav:
  - Home: index.md
  - Documentation:
    - Quick Start: quick-start.md
    - Why Openterface: why-openterface-minikvm.md
    - Use Cases: use-cases.md
    - Specifications: specifications.md
    - What's in the Box: whats-in-the-box.md
    - How It Works: how-it-works.md
    - Comparison: comparison.md
    - FAQs: faq.md
    # - Concepts: concepts.md
    # - App: software.md

  - FAQs: faq.md
  - Posts:
    - blog/index.md
  # - Topics: tags.md
  - About:
    - Contact: contact.md
    - Acknowledgements: acknowledgements.md
    - Policies:
      - Privacy Policy: privacy-policy.md
      - Terms of Service: terms-of-service.md
      - Return, Refunds & Warranty: return-refunds-warranty.md
  # - Download: download.md
  - Subreddit: https://www.reddit.com/r/Openterface_miniKVM/